Move test configs to individual packages
prosopo/captcha pull request #1134
Opened 2024-04-04 11:02 UTC by forgetso

2024-04-04 14:15 UTC, goastler requested changes

2024-04-04 14:15 UTC, goastler commented on package.json
> +        "test": "npm run --workspaces --if-present test",
rogue `--if-present`?

2024-04-04 14:17 UTC, forgetso commented on package.json
> +        "test": "npm run --workspaces --if-present test",
Removed.

2024-04-04 14:18 UTC, goastler submitted a review, later dismissed

2024-04-08 08:11 UTC, goastler approved these changes
:rocket:

2024-04-08 08:11 UTC, merged