Cron schedule for dumping in external mongo
prosopo/captcha pull request #1264
Opened 2024-06-05 12:59 UTC by HughParry

2024-06-05 13:50 UTC, forgetso requested changes

2024-06-05 13:50 UTC, forgetso commented on packages/database/src/captchaDatabase/captchaDatabse.ts
> +const storedCaptchaSchema = new mongoose.Schema({
Use `UserCommitmentRecordSchema` from `captcha/packages/types-database/src/types/mongo.ts`

2024-06-05 13:50 UTC, forgetso commented on packages/database/src/databases/mongo.ts
> +            { $set: { stored: true } },
Does `stored` need to be added to `UserCommitmentRecordSchema` and `UserCommitmentRecord`?

2024-06-05 13:50 UTC, forgetso commented on packages/provider/src/batch/mongoBatch.ts
What is this?

2024-06-05 13:50 UTC, forgetso commented on packages/provider/src/captchaScheduler.ts
> +export async function batchCommitScheduler(pair: KeyringPair, config: ProsopoConfigOutput) {
Calling this batch commit is pretty confusing considering the old batch commit to contract stuff that's kicking about. How about `storeCaptchasExternally`?

Is the contents of this file meant to be in the empty file above?

2024-06-05 13:50 UTC, forgetso commented on packages/provider/src/captchaScheduler.ts
> +    job.start()
How is this scheduler started?

2024-06-05 13:56 UTC, HughParry commented on packages/database/src/captchaDatabase/captchaDatabse.ts
> +const storedCaptchaSchema = new mongoose.Schema({
Done

2024-06-05 13:57 UTC, HughParry commented on packages/database/src/databases/mongo.ts
> +            { $set: { stored: true } },
Yeah it's the most straightforward way to make sure that records are only added to mongo once

2024-06-05 13:58 UTC, forgetso commented on packages/database/src/databases/mongo.ts
> +            { $set: { stored: true } },
Sure, but `stored` is missing from the types. I think it needs to be added to `UserCommitmentRecordSchema` and `UserCommitmentRecord`

2024-06-05 14:02 UTC, HughParry commented on packages/provider/src/captchaScheduler.ts
> +export async function batchCommitScheduler(pair: KeyringPair, config: ProsopoConfigOutput) {
Changed

2024-06-05 14:02 UTC, HughParry commented on packages/provider/src/captchaScheduler.ts
> +    job.start()
Forgot to add to cli, added now

2024-06-05 14:06 UTC, HughParry commented on packages/database/src/databases/mongo.ts
> +            { $set: { stored: true } },
Ah gotcha, just added

2024-06-12 14:22 UTC, HughParry commented on packages/provider/src/captchaScheduler.ts
> +    job.start()
Resolved since added now

2024-06-12 15:57 UTC, forgetso requested changes
Close the database connection and we're good to go

2024-06-12 17:28 UTC, forgetso approved these changes

2024-06-12 17:28 UTC, merged