Store something on each request. Update PoW types. Additional checks
prosopo/captcha pull request #1336
Opened 2024-08-22 14:37 UTC by forgetso

We need to be able to see how many requests for Proof of Work captcha have been made

- [x] This PR changes the PoW generation mechanism to generate a record at the point of challenge creation. Various attributes are modified by subsequent requests to mark the stage the challenge is at (requested, userChecked, serverChecked).
- [x] The PoW types also receive a fairly big refactor.
- [x] The signatures are changed to be requestHash signatures for image captcha. Signature for PoW captcha remain as challenge (provider) and timestamp (user).

2024-08-22 15:51 UTC, goastler requested changes, later dismissed

2024-08-22 15:51 UTC, goastler commented on packages/provider/src/api/captcha.ts
> +const NO_IP_ADDRESS = "NO_IP_ADDRESS";
probably want to chuck 'as const' on the end of this for better typing

2024-08-26 09:21 UTC, HughParry commented on dev/scripts/src/setup/setup.ts
>      // If no PROSOPO_SITE_KEY is present, we will register a test account like //Eve.
Stale comments are pretty confusing here

2024-08-26 09:25 UTC, HughParry commented on packages/api/src/api/ProviderApi.ts
> +      captchas,
all of these should be api params: blah

2024-08-26 10:03 UTC, HughParry commented on packages/provider/src/api/captcha.ts
> +        captchas: taskData.captchas.map((captcha: Captcha) => ({
[ApiParams.captchas] or something

2024-08-26 10:21 UTC, HughParry commented on packages/provider/src/tasks/powCaptcha/powTasks.ts
> +    if (challengeRecord.ipAddress !== ipAddress) {
If we could drop this for now please

2024-08-26 10:22 UTC, HughParry commented on packages/provider/src/tasks/powCaptcha/powTasksUtils.ts
> +  return validateSolution(nonce, challenge, difficulty);
can we drop this func now that it just passes to a different one?

2024-08-26 10:22 UTC, HughParry commented on packages/provider/src/tasks/powCaptcha/powTasksUtils.ts
> +  return verifyRecency(challenge, timeout);
can we drop this func now that it just passes to a different one?

2024-08-26 10:24 UTC, HughParry reviewed
few comments

2024-08-26 10:51 UTC, forgetso commented on dev/scripts/src/setup/setup.ts
>      // If no PROSOPO_SITE_KEY is present, we will register a test account like //Eve.
Removed

2024-08-26 10:53 UTC, forgetso commented on packages/provider/src/tasks/powCaptcha/powTasks.ts
> +    if (challengeRecord.ipAddress !== ipAddress) {
Dropped

2024-08-26 15:44 UTC, HughParry approved these changes

2024-08-26 15:45 UTC, merged