Image server
prosopo/captcha pull request #346
Opened 2023-08-07 10:59 UTC by goastler

2023-08-07 11:01 UTC, goastler commented
fixes #234

2023-08-07 18:53 UTC, forgetso commented on packages/file-server/env.example
> +REMOTES="http://localhost:3001" # list of remote servers to proxy requests to (can be JSON array)
I hi

2023-08-07 18:56 UTC, forgetso approved these changes

2023-08-07 18:56 UTC, forgetso commented on packages/file-server/env.example
> +PORT=3000 # port to run the server on
I think the default port should be in line with the rest of our ports. We've used `9228` to `9231` so this one should perhaps be `9232`

2023-08-07 18:56 UTC, forgetso requested changes
Looks good. Just one very small env file query.

2023-08-08 07:00 UTC, goastler commented on packages/file-server/env.example
> +PORT=3000 # port to run the server on
good shout, I agree :)

2023-08-08 18:49 UTC, forgetso approved these changes

2023-08-08 18:50 UTC, merged