Implement basic networks package
prosopo/captcha pull request #652
Opened 2023-09-29 09:02 UTC by forgetso

2023-09-29 09:09 UTC, forgetso commented
- [ ] TODO: Obtain SS58_FORMAT and PAIR_TYPE from polkadot package

2023-10-19 11:13 UTC, HughParry requested changes

2023-10-19 11:13 UTC, HughParry commented on demos/client-example/src/config.ts
> +const getWeb2 = (): boolean | undefined => {
Could be much shorter snippet. If we default to true (which is potentailly expected behaviour) then:

return !(process.env.REACT_APP_WEB2 === 'false')

---

if we require undefined then something like:

process.env.REACT_APP_WEB2 === 'true' ? true : process.env.REACT_APP_WEB2 === 'false' ? false : undefined;

2023-10-19 11:13 UTC, HughParry commented on dev/scripts/src/scripts/getNetworks.ts
> +    selectableNetworks.forEach((network) => {
Can we be consistent on using functional methods vs for loops within files(sorry this one pretty nitpicky)

2023-10-19 12:15 UTC, forgetso commented on dev/scripts/src/scripts/getNetworks.ts
> +    selectableNetworks.forEach((network) => {
This wasn't meant to be in the PR. I've deleted it.

2023-10-19 12:15 UTC, forgetso commented on demos/client-example/src/config.ts
> +const getWeb2 = (): boolean | undefined => {
Changed

2023-10-19 12:18 UTC, HughParry approved these changes

2023-10-19 12:27 UTC, merged