Including optional time for isValid in server
prosopo/captcha pull request #780
Opened 2023-11-09 14:38 UTC by HughParry

2023-11-09 14:39 UTC, forgetso requested changes
Looks good, could you stick the time stuff in a separate function?

2023-11-13 09:16 UTC, goastler requested changes, later dismissed

2023-11-13 09:16 UTC, goastler commented on packages/types/src/provider/api.ts
> +    [ApiParams.maxVerifiedTime]: number().optional(),
is this something the client could fudge?

2023-11-13 09:16 UTC, goastler commented on packages/provider/src/tasks/tasks.ts
> +    async getBlockTimeMs(): Promise<number> {
this should be a fn on the contract api, no?

2023-11-13 09:16 UTC, goastler commented on packages/provider/src/tasks/tasks.ts
> +    async getCurrentBlockNumber(): Promise<number> {
this should be a fn on the contract api, no?

2023-11-23 11:20 UTC, forgetso approved these changes

2023-11-23 11:22 UTC, forgetso approved these changes

2023-11-23 11:23 UTC, merged