Retry random provider within observable
prosopo/captcha pull request #85
Opened 2023-05-30 12:25 UTC by HughParry

2023-05-30 13:05 UTC, goastler requested changes
need to discuss some of the changes :)

2023-05-30 13:05 UTC, goastler commented on packages/procaptcha/src/modules/Manager.ts
> +                    (error) => console.error('Failed to fetch challenge and block number', error)
this should be some kind of callback rather than silently logging to console

2023-05-30 13:05 UTC, goastler commented on packages/procaptcha/src/modules/Manager.ts
>          } catch (err) {
the stuff inside the defer call won't be caught by this catch now. Would it be better to put the whole of this fn inside the defer fn perhaps?

2023-05-30 13:05 UTC, goastler commented on packages/procaptcha/src/modules/Manager.ts
> +    const fetchCaptchaChallenge = async (contract, account, config) => {
good work breaking these up into fns

2023-05-30 13:05 UTC, goastler commented on packages/procaptcha/src/modules/Manager.ts
> +                            unsubscribe()
that's some gnarly subscriptions there haha

2023-05-30 13:05 UTC, goastler commented on packages/procaptcha/src/modules/Manager.ts
> +function timoutSetup(
who's tim and why is he out? :joy:

2023-05-30 14:10 UTC, goastler commented on packages/procaptcha/src/modules/Manager.ts
>          } catch (err) {
nvm, moot point because the isHuman checks would be repeated and we don't want that to happen

2023-09-20 10:12 UTC, HughParry commented
Closing since now ancient code from when I joined.

Ticket in to resolve this here https://github.com/prosopo/captcha/issues/574

2023-09-20 10:12 UTC, closed without merging