fixes #87
prosopo/captcha pull request #88
Opened 2023-05-30 19:43 UTC by forgetso

2023-05-30 19:44 UTC, goastler requested changes, later dismissed

2023-05-30 19:44 UTC, goastler commented on dev/src/setup/provider.ts
> +    console.log(registeredProvider)
left over debug?

2023-05-31 15:52 UTC, forgetso commented on dev/src/setup/provider.ts
> +    console.log(registeredProvider)
yep, removed

2023-06-01 09:27 UTC, HughParry approved these changes

2023-06-01 09:29 UTC, merged